wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725035911
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.19
      5: 0.17.8
      6: 4.44.2
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 50
d_model:
  desc: null
  value: 256
d_vocab:
  desc: null
  value: 2500
learning_rate:
  desc: null
  value: 0.001
nhead:
  desc: null
  value: 8
num_epochs:
  desc: null
  value: 1
num_layers:
  desc: null
  value: 3
